#!/usr/bin/env bash
set -euo pipefail

if [[ -t 1 ]] && [[ -z "${NO_COLOR:-}" ]]; then
  COLOR_INFO="\033[36m"
  COLOR_WARN="\033[33m"
  COLOR_ERROR="\033[31m"
  COLOR_RESET="\033[0m"
else
  COLOR_INFO=""
  COLOR_WARN=""
  COLOR_ERROR=""
  COLOR_RESET=""
fi

info() {
  echo -e "${COLOR_INFO}INFO:${COLOR_RESET} $*"
}

warn() {
  echo -e "${COLOR_WARN}WARNING:${COLOR_RESET} $*"
}

error() {
  echo -e "${COLOR_ERROR}ERROR:${COLOR_RESET} $*"
}

CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
CONFIG_DIR="${CONFIG_HOME}/vaultsh"
CONFIG_FILE="${CONFIG_DIR}/config"

NON_INTERACTIVE=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --non-interactive|--yes)
      NON_INTERACTIVE=1
      shift
      ;;
    *)
      warn "Unknown argument: $1"
      shift
      ;;
  esac
done

info "vaultsh setup"
info "Config file: $CONFIG_FILE"

prompt_default() {
  local var_name="$1"
  local prompt="$2"
  local default="$3"

  if [[ $NON_INTERACTIVE -eq 1 ]]; then
    local value="${!var_name:-$default}"
    printf '%s' "$value"
    return
  fi

  local current="${!var_name:-$default}"
  read -r -p "$prompt [$current]: " input
  if [[ -z "$input" ]]; then
    printf '%s' "$current"
  else
    printf '%s' "$input"
  fi
}

mkdir -p "$CONFIG_DIR"

if [[ -f "$CONFIG_FILE" ]] && [[ $NON_INTERACTIVE -eq 0 ]]; then
  warn "Config file already exists at $CONFIG_FILE"
  read -r -p "Overwrite existing config? [y/N]: " answer
  case "$answer" in
    [Yy]*)
      info "Overwriting existing config file"
      ;;
    *)
      info "Keeping existing config file. Setup complete."
      exit 0
      ;;
  esac
fi

VAULTSH_ADDR_VALUE="$(prompt_default VAULTSH_ADDR 'VAULTSH_ADDR (Vault server URL)' 'https://127.0.0.1:8200')"
VAULTSH_READER_ROLE_VALUE="$(prompt_default VAULTSH_READER_ROLE 'VAULTSH_READER_ROLE (OIDC reader role)' 'reader')"
VAULTSH_OPERATOR_ROLE_VALUE="$(prompt_default VAULTSH_OPERATOR_ROLE 'VAULTSH_OPERATOR_ROLE (OIDC operator role)' 'operator')"
VAULTSH_NAV_ROOT_VALUE="$(prompt_default VAULTSH_NAV_ROOT 'VAULTSH_NAV_ROOT (Browse start path, must end with /)' 'secret/')"

# Ensure nav root ends with /
if [[ "$VAULTSH_NAV_ROOT_VALUE" != */ ]]; then
  VAULTSH_NAV_ROOT_VALUE="${VAULTSH_NAV_ROOT_VALUE}/"
fi

# Optional session probe for session check (when token lookup returns 403)
VAULTSH_SESSION_PROBE_PATH_VALUE="${VAULTSH_SESSION_PROBE_PATH:-}"
VAULTSH_SESSION_PROBE_FIELD_VALUE="${VAULTSH_SESSION_PROBE_FIELD:-}"
if [[ $NON_INTERACTIVE -eq 0 ]]; then
  read -r -p "VAULTSH_SESSION_PROBE_PATH (optional, for session-check fallback; Enter = skip) [$VAULTSH_SESSION_PROBE_PATH_VALUE]: " probe_path_input
  [[ -n "$probe_path_input" ]] && VAULTSH_SESSION_PROBE_PATH_VALUE="$probe_path_input"
  read -r -p "VAULTSH_SESSION_PROBE_FIELD (optional; Enter = skip) [$VAULTSH_SESSION_PROBE_FIELD_VALUE]: " probe_field_input
  [[ -n "$probe_field_input" ]] && VAULTSH_SESSION_PROBE_FIELD_VALUE="$probe_field_input"
fi

cat > "$CONFIG_FILE" <<EOF
# vaultsh configuration
# Generated by setup_vaultsh.sh. Environment variables override these values.

VAULTSH_ADDR="\${VAULTSH_ADDR:-$VAULTSH_ADDR_VALUE}"
VAULTSH_READER_ROLE="\${VAULTSH_READER_ROLE:-$VAULTSH_READER_ROLE_VALUE}"
VAULTSH_OPERATOR_ROLE="\${VAULTSH_OPERATOR_ROLE:-$VAULTSH_OPERATOR_ROLE_VALUE}"
VAULTSH_NAV_ROOT="\${VAULTSH_NAV_ROOT:-$VAULTSH_NAV_ROOT_VALUE}"
VAULTSH_SESSION_PROBE_PATH="\${VAULTSH_SESSION_PROBE_PATH:-$VAULTSH_SESSION_PROBE_PATH_VALUE}"
VAULTSH_SESSION_PROBE_FIELD="\${VAULTSH_SESSION_PROBE_FIELD:-$VAULTSH_SESSION_PROBE_FIELD_VALUE}"
EOF

info "Configuration written to $CONFIG_FILE"
info "Setup complete. Run 'vaultsh' to start."
